name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3

    - name: 🟢 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: 📦 Install dependencies
      run: |
        cd app
        npm install

    - name: ✅ Run linter (optional)
      run: |
        cd app
        npx eslint . || true

    - name: 🧪 Run tests (optional)
      run: |
        cd app
        npm test || echo "No tests defined"
